<?php
require_once dirname(__DIR__, 2) . '/app/helpers/auth.php';
require_role('user');
require_once dirname(__DIR__, 2) . '/app/helpers/db.php';
require_once dirname(__DIR__, 2) . '/vendor/fpdf/fpdf.php';

$user_id = $_SESSION['user']['id'];
$appt_id = isset($_GET['id']) ? intval($_GET['id']) : 0;

$conn = get_db_connection();
$stmt = $conn->prepare("SELECT * FROM appointments WHERE id = ? AND user_id = ?");
$stmt->bind_param('ii', $appt_id, $user_id);
$stmt->execute();
$appt = $stmt->get_result()->fetch_assoc();
$stmt->close();
$conn->close();

if (!$appt) {
    die("Appointment not found.");
}

$pdf = new FPDF();
$pdf->AddPage();
$pdf->SetFont('Arial', 'B', 16);
$pdf->Cell(0, 12, 'Appointment Information', 0, 1, 'C');
$pdf->Ln(8);
$pdf->SetFont('Arial', '', 12);

$pdf->Cell(50, 10, 'Reference #:', 0, 0);
$pdf->Cell(0, 10, '#APPT-' . str_pad($appt['id'], 3, '0', STR_PAD_LEFT), 0, 1);
$pdf->Cell(50, 10, 'Complaint:', 0, 0);
$pdf->Cell(0, 10, $appt['complaint'], 0, 1);
$pdf->Cell(50, 10, 'Date:', 0, 0);
$pdf->Cell(0, 10, date('F d, Y', strtotime($appt['preferred_date'])), 0, 1);
$pdf->Cell(50, 10, 'Time Slot:', 0, 0);
$pdf->Cell(0, 10, $appt['time_slot'], 0, 1);
$pdf->Cell(50, 10, 'Status:', 0, 0);
$pdf->Cell(0, 10, $appt['status'], 0, 1);

$pdf->Ln(10);
$pdf->SetFont('Arial', 'I', 10);
$pdf->Cell(0, 8, 'Generated by Barangay Clinic Online Appointment System', 0, 1, 'C');

$pdf->Output('I', 'appointment_' . $appt['id'] . '.pdf');
exit; 