name: Deploy PHP to Hostinger via SFTP

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Upload to Hostinger via SFTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install lftp
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp

      - name: Deploy files to Hostinger
        env:
          SFTP_HOST: ${{ secrets.SFTP_HOST }}
          SFTP_USERNAME: ${{ secrets.SFTP_USERNAME }}
          SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
          SFTP_PORT: ${{ secrets.SFTP_PORT }}
          SFTP_TARGET: ${{ secrets.SFTP_TARGET }}
        run: |
          lftp -d -u "$SFTP_USERNAME","$SFTP_PASSWORD" -p $SFTP_PORT sftp://$SFTP_HOST -e "
            mirror -R public_html $SFTP_TARGET --delete --verbose;
            bye
          "
